########   TRY BELOW IP TO CHECK JAVA  BASED APP DEPLOYED 
########    http://52.66.235.163/

stages:
  - build
  - docker_build
  - docker_push
build:
  stage: build
  script:
    - sudo apt update -y
    - sudo apt install -y docker.io default-jdk maven
    - mvn clean package -DskipTests 
  tags:
    - runner1

docker_build:
  stage: docker_build
  script:
    - ls -l
    - docker images
    - docker build -t dhairyashil/knovator:6 .
    - docker image prune 
    - docker images
  tags:
    - runner1



docker_push:
  stage: docker_push
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push dhairyashil/knovator:6
    - docker run -d -p 80:8080 dhairyashil/knovator:6 
  tags:
    - runner1

 
########   TRY BELOW IP TO CHECK JAVA  BASED APP DEPLOYED 
########    http://52.66.235.163/

